### ISSUE TITLE
NoMethodError (undefined method `custom_field_id_start' for nil:NilClass):

### ISSUE THREAD

**Issue by ricardoamm** [aki360P/redmine_resource_booking_system#2]
NoMethodError (undefined method `custom_field_id_start' for nil:NilClass):

plugins/redmine_resource_booking_system/app/controllers/rrbs_bookings_controller.rb:18:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by aki360P** [comment]
Please complete plugin settings in project setting menu. Screenshots will be helpful.
I'm planning to replace the custom_field to some modern function at next version.

**Comment by fikriast** [comment]
i have some issue, please help me :

plugins/redmine_resource_booking_system/app/controllers/rrbs_bookings_controller.rb:18:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by fikriast** [comment]
![image](https://user-images.githubusercontent.com/28298975/71391865-820aee80-2638-11ea-9c7a-1f6a4d2adb7a.png)

when I click on the booking menu I get the error, for the project configuration I have done accordingly.

**Comment by aki360P** [comment]
I missed this message, sorry !
Plugin setting is little bit confusing. Please check plugin settings.

I know this plugin needs check function to make sure plugin settings.

**Comment by meetdileep** [comment]
Same issue. "Internal Error" after clicking on Booking.
